-- 코드를 입력하세요
SELECT first_half.flavor
FROM FIRST_HALF, ICECREAM_INFO
WHERE FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
AND FIRST_HALF.TOTAL_ORDER > 3000;